create table stats_by_day
(
    ts                   timestamptz DEFAULT now() NOT NULL,
    updated_at           timestamptz DEFAULT now() NOT NULL,
    placement_type       SMALLINT    DEFAULT 0     NOT NULL,
    valid_type           SMALLINT    DEFAULT 0     NOT NULL,
    seller_code          SMALLINT    DEFAULT 0     NOT NULL,    
    seller_trading_type  SMALLINT    DEFAULT 0     NOT NULL,
    buyer_trading_type   SMALLINT    DEFAULT 0     NOT NULL,
    seller_deal_type     SMALLINT    DEFAULT 0     NOT NULL,
    buyer_deal_type      SMALLINT    DEFAULT 0     NOT NULL,
    os_type              SMALLINT    DEFAULT 0     NOT NULL,
    drop_type            SMALLINT    DEFAULT 0     NOT NULL,
    interception_type    SMALLINT    DEFAULT 0     NOT NULL,
    ext_sint_1           SMALLINT    DEFAULT 0     NOT NULL,
    ext_sint_2           SMALLINT    DEFAULT 0     NOT NULL,
    ext_sint_3           SMALLINT    DEFAULT 0     NOT NULL,
    ext_sint_4           SMALLINT    DEFAULT 0     NOT NULL,
    ext_sint_5           SMALLINT    DEFAULT 0     NOT NULL,
    dsp_id               INTEGER     DEFAULT 0     NOT NULL,
    dsp_app_id           INTEGER     DEFAULT 0     NOT NULL,
    dsp_app_placement_id INTEGER     DEFAULT 0     NOT NULL,
    pub_id               INTEGER     DEFAULT 0     NOT NULL,
    pub_app_id           INTEGER     DEFAULT 0     NOT NULL,
    pub_app_placement_id INTEGER     DEFAULT 0     NOT NULL,
    ext_id_1             INTEGER     DEFAULT 0     NOT NULL,
    ext_id_2             INTEGER     DEFAULT 0     NOT NULL,
    ext_id_3             INTEGER     DEFAULT 0     NOT NULL,
    ext_id_4             INTEGER     DEFAULT 0     NOT NULL,
    ext_id_5             INTEGER     DEFAULT 0     NOT NULL,
    adx_cost_in_micro    BIGINT      DEFAULT 0     NOT NULL,
    adx_revenue_in_micro BIGINT      DEFAULT 0     NOT NULL,
    events               BIGINT      DEFAULT 0     NOT NULL,
    seller_request       BIGINT      DEFAULT 0     NOT NULL,
    adx_intercept        BIGINT      DEFAULT 0     NOT NULL,
    to_buyer_request     BIGINT      DEFAULT 0     NOT NULL,
    buyer_bid            BIGINT      DEFAULT 0     NOT NULL,
    buyer_no_bid         BIGINT      DEFAULT 0     NOT NULL,
    buyer_timeout        BIGINT      DEFAULT 0     NOT NULL,
    buyer_error          BIGINT      DEFAULT 0     NOT NULL,
    adx_bid              BIGINT      DEFAULT 0     NOT NULL,
    adx_no_bid           BIGINT      DEFAULT 0     NOT NULL,
    adx_drop             BIGINT      DEFAULT 0     NOT NULL,
    win_notice           BIGINT      DEFAULT 0     NOT NULL,
    impression           BIGINT      DEFAULT 0     NOT NULL,
    click                BIGINT      DEFAULT 0     NOT NULL,
    download_started     BIGINT      DEFAULT 0     NOT NULL,
    download_completed   BIGINT      DEFAULT 0     NOT NULL,
    install_started      BIGINT      DEFAULT 0     NOT NULL,
    install_completed    BIGINT      DEFAULT 0     NOT NULL,

    PRIMARY KEY (ts, placement_type, valid_type, seller_code, seller_trading_type, buyer_trading_type, seller_deal_type,
                 buyer_deal_type, os_type, drop_type, interception_type, ext_sint_1, ext_sint_2, ext_sint_3,
                 ext_sint_4, ext_sint_5, dsp_id, dsp_app_id, dsp_app_placement_id, pub_id, pub_app_id,
                 pub_app_placement_id, ext_id_1, ext_id_2, ext_id_3, ext_id_4, ext_id_5)
)
    PARTITION BY RANGE (ts);
