create table ady_event_file_meta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name text not null default '',
    file_path text not null default '',
    file_lines int not null default 0,
    status int not null default 0,
    offset_sum bigint not null default 0,
    host_name text not null default '',
    duration int not null default 0,
    start_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    loaded_at timestamptz not null default to_timestamp(0)
);
